[Details]
Icon = "assets/icons/icon.png"
Name = "SshProxy"
ID = "com.bytemystery.sshproxy"
Version = "0.2.5"
Build = 166

[LinuxAndBSD]
GenericName = "SshProxy"
Categories = ["Network"]
Comment = "SOCKS5 and HTTP proxy over ssh"
Keywords = ["ssh", "socks5", "http", "proxy"]
